import { createApp } from 'vue';
import App from './App.vue';
import { createPinia } from 'pinia';
import router from './router';
import Pilot from './packages';
const pinia = createPinia();
const app = createApp(App);
app.use(pinia);
app.use(Pilot);
app.use(router);
app.mount('#app');
